.TH rscaffold 1 rscaffold\-0.0.0
.SH NAME
rscaffold \- generate scaffolding for a ruby gem
.SH SYNOPSIS
.B rscaffold PROJECT_NAME
.SH DESCRIPTION
.B rscaffold
generates most things you would want in a basic ruby project.
.SH OPTIONS
.LP
.B --help
Print a brief usage message.
.SH EXAMPLES
.LP
.B rscaffold 
.SH FILES
.SH SEE ALSO
.TP
.BR ruby(1)
.TP
.IR 
.SH BUGS
Probably.
.SH LICENSE
Copyright  Noah Birnel

.sp
MIT License
